### ISSUE TITLE
Error: It appears that you're using glslify in browserify without its transform applied.

### ISSUE THREAD

**Issue by stirlingpoon** [plotly/react-plotly.js#13]

**Comment by rreusser** [comment]
Thanks for the issue! I'll need to know more about what you're trying to do in order to debug it, but if you're using webpack you'll have to follow [these instructions](https://github.com/plotly/plotly.js#building-plotlyjs-with-webpack) and add to webpack.config.js:

```javascript
...
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'ify-loader'
            }
        ]
    },
...
```

**Comment by rreusser** [comment]
Alternative, you can use the [factory version of the component](https://github.com/plotly/react-plotly.js#with-external-plotlyjs) and inject a [CDN version of Plotly.js](https://plot.ly/javascript/getting-started/#plotlyjs-cdn) in order to avoid needing to build it from scratch.

**Comment by rreusser** [comment]
I've added a note to the instructions regarding webpack: https://github.com/plotly/react-plotly.js#with-bundled-plotlyjs

**Comment by stirlingpoon** [comment]
Thanks for the quick update, I didn't realize I filed a incomplete bug. The issue is that I can't directly edit the Webpack config files. See #14 for the full context.

**Comment by kausti** [comment]
Hi,

I have the exact same error. 
Following the webpack config from https://github.com/rreusser/plotly-webpack/blob/master/webpack.config.js

Here is my webpack.config.js

 ```
module: {
     //Will ignore the modules fs, path, xlsx, request, vertx, and react-native modules
      rules: [
      {
        test: /.jsx?$/,
        exclude: /node_modules/,
        include: path.join(__dirname, 'assets/js/'),
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              presets: [
                ['es2015', { modules: false }],
                'react',
                "eslatest-node6", 
                "stage-3", "stage-2"
              ],
              plugins: [
                  "transform-es2015-destructuring",
                  "transform-es2015-parameters",
                  'transform-object-rest-spread',
              ]
            }
          },
          {
            loader: 'ify-loader',
          },
          {
            loader: 'transform-loader?plotly.js/tasks/util/compress_attributes.js',
          }

        ]
      },
      
    ]
  }
```
I am still getting this error. However, this happens only when I use react-plotly.js.
```
import createPlotlyComponent from 'react-plotly.js'
//See the list of possible plotly bundles at https://github.com/plotly/plotly.js/blob/master/dist/README.md#partial-bundles or roll your own
import Plotly from 'plotly.js/dist/plotly-cartesian'
const PlotlyComponent = createPlotlyComponent(Plotly)
```

When I use plotly.js without the wrapper as follows, it works

```
import * as PlotlyScatter from 'plotly.js/lib/scatter'
import * as PlotlyHeatmap from 'plotly.js/lib/heatmap'
PlotlyCore.register([PlotlyHeatmap])
```

Any ideas please?

**Comment by rreusser** [comment]
@kausti First of all, you *might* need `test: /\.js$/` in order to specify which files are transformed. I'm less experienced with webpack so I'm not 100% sure.

Second, the `dist/` versions of plotly.js already have the transforms applied so that I don't think it's necessary to apply them separately via the `ify-loader` plugin. If you're using the `dist/` version yo might just be able to cut that ot.

Finally, (and totally guessing but maybe this is what made it trickier to debug the above two points), it looks like you've done something slightly inconsistent in your import. There are two ways to import the component:

1. With `plotly.js` you've required yourself via a script tag or separate import:
    
    ```javascript
    import createPlotlyComponent from 'react-plotly.js/factory'
    import Plotly from 'plotly.js/dist/plotly-cartesian'
    const PlotlyComponent = createPlotlyComponent(Plotly)
    ```

2. Or with `plotly.js` included automatically by the component:
    
    ```javascript
    import PlotlyComponent from 'react-plotly.js'
    ```

(Small note: I changed [example 1 in the readme](https://github.com/plotly/react-plotly.js#with-external-plotlyjs) to match the function name `createPlotlyComponent`, which I hope makes it more clear which setup is which throughout the readme.)

In your code above, it looks like you've imported the component itself. Please note that the main import *imports plotly.js itself*. That means your example is trying to include it twice: once from `react-plotly.js` and once from `plotly.js/dist/plotly-cartesian`. The solution is to import `react-plotly.js/factory` instead.

Apologies on the confusion, but it's a result of the fact that there are many different ways in which people need to get plotly into their projects. Since ES6 doesn't have conditional imports, the separate entry points (the component vs. the factory) were the only way we could make that happen. Hopefully that will solve the problem, but please let me know if that's not the case or if there's anything you think we could do to make this more clear. Thanks!

**Comment by bpostlethwaite** [comment]
Updated docs at:
https://github.com/plotly/react-plotly.js#build-with-webpack
and
https://github.com/plotly/react-plotly.js#build-with-create-react-app

If there is something else we can do let us know!
